server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This allows Vue Router to handle the routing (SPA fallback)
        try_files $uri $uri/ /index.html;
    }
}
